name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: "22 2 * * *" # Every night at 2:22 am
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  BASE_PATH: "/${{ github.event.repository.name }}"
  GITHUB_USERNAME: ${{ github.repository_owner }}
  SPATIAL_INDEX_TAG: "precincts-v1" # GitHub release tag

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # LFS removed

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download latest precincts spatial index from GitHub Release
        run: npm run download-precincts-spatial-index

      - name: Download cache DB from GitHub Release
        env:
          GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        run: npx tsx scripts/eventDb/releaseManager.ts download-cache

      - name: Run events db builder – generates/updates cache sqlite db
        env:
          GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: npm run build-events-db

      - name: Show contents of build/summary.txt
        run: cat build/summary-last.txt

      - name: Version and copy SQLite DB
        run: npx tsx scripts/eventDb/versionAndCopyDb.ts

      - name: Upload log and updated cache DB to GitHub Release
        env:
          GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        run: |
          npx tsx scripts/eventDb/releaseManager.ts upload-log
          npx tsx scripts/eventDb/releaseManager.ts upload-cache

      - name: Download region sqlite and json files from Release
        run: npx tsx scripts/downloadRegionData.ts

      - name: Build static site
        env:
          VITE_MAPTILER_API_KEY: ${{ secrets.VITE_MAPTILER_API_KEY }}
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
